# Docker Compose syntax version. Requires Docker Engine 1.12.0+
version: '2.1'

# Create a subnet that all services can run on
networks:
  services-network:
    driver: bridge

# Docker services
services:
  # redis container
  redis:
    image: redis:3
    networks:
      - services-network
    restart: always

  # redis commander
  redis-commander:
    build:
      context: ./commander
      dockerfile: commander.docker
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - services-network
    restart: always
